GET http://localhost:8080/
# the request above returns a json object with all professional data for Nathan Birch. No database is connected.
# --Test ALL USERS
GET http://localhost:8080/users
# ---Render ALL USERS---
GET https://creestian.onrender.com/users
# ---Render SINGLE USER
GET https://creesian.onrender.com/users/66f1c02e976a8ebadc7cce9b